apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <value>
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: <value>-{{ .Release.Namespace }}
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      container_type: <value>
      namespace: {{ .Release.Namespace }}
---