apiVersion: v1
kind: Secret
metadata:
  name: <value>
  namespace: {{ .Values.customer }}-{{ .Values.<value> }}
data:
  <value>: {{ .Values.<value> | b64enc }}
  <value>: {{ .Values.<value> | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: <value>
  namespace: {{ .Values.<value> }}-{{ .Values.<value> }}
stringData:
  password: {{ .Values.<value> }}
type: Opaque
---