apiVersion: v1
kind: Service
metadata:
  name: <value>-application
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: <value>
      protocol: TCP
      targetPort: 8080
  selector:
    app: <value>-application
---